/**
 * Full ISO 3166-1 country list for the billing address country select.
 *
 * Unlike shipping (always Cuba — the store's single region/country), billing
 * is not tied to the delivery zone: a customer can pay from/bill to any
 * country, so this is a static list independent of `cart.region.countries`
 * (which only ever contains "cu"). Codes are lowercase iso_2, matching the
 * convention already used by `country_code` across the storefront/backend.
 */
const RAW_COUNTRIES: [string, string][] = [
  ["cu", "Cuba"],
  ["ar", "Argentina"],
  ["bo", "Bolivia"],
  ["br", "Brasil"],
  ["ca", "Canadá"],
  ["cl", "Chile"],
  ["co", "Colombia"],
  ["cr", "Costa Rica"],
  ["do", "República Dominicana"],
  ["ec", "Ecuador"],
  ["sv", "El Salvador"],
  ["es", "España"],
  ["us", "Estados Unidos"],
  ["gt", "Guatemala"],
  ["hn", "Honduras"],
  ["mx", "México"],
  ["ni", "Nicaragua"],
  ["pa", "Panamá"],
  ["py", "Paraguay"],
  ["pe", "Perú"],
  ["pr", "Puerto Rico"],
  ["uy", "Uruguay"],
  ["ve", "Venezuela"],
  ["af", "Afganistán"],
  ["al", "Albania"],
  ["de", "Alemania"],
  ["ad", "Andorra"],
  ["ao", "Angola"],
  ["ag", "Antigua y Barbuda"],
  ["sa", "Arabia Saudita"],
  ["dz", "Argelia"],
  ["am", "Armenia"],
  ["au", "Australia"],
  ["at", "Austria"],
  ["az", "Azerbaiyán"],
  ["bs", "Bahamas"],
  ["bh", "Baréin"],
  ["bd", "Bangladés"],
  ["bb", "Barbados"],
  ["be", "Bélgica"],
  ["bz", "Belice"],
  ["bj", "Benín"],
  ["by", "Bielorrusia"],
  ["mm", "Birmania"],
  ["ba", "Bosnia y Herzegovina"],
  ["bw", "Botsuana"],
  ["bn", "Brunéi"],
  ["bg", "Bulgaria"],
  ["bf", "Burkina Faso"],
  ["bi", "Burundi"],
  ["bt", "Bután"],
  ["cv", "Cabo Verde"],
  ["kh", "Camboya"],
  ["cm", "Camerún"],
  ["qa", "Catar"],
  ["td", "Chad"],
  ["cn", "China"],
  ["cy", "Chipre"],
  ["vc", "San Vicente y las Granadinas"],
  ["km", "Comoras"],
  ["cg", "Congo"],
  ["cd", "Congo (RD)"],
  ["kp", "Corea del Norte"],
  ["kr", "Corea del Sur"],
  ["ci", "Costa de Marfil"],
  ["hr", "Croacia"],
  ["dk", "Dinamarca"],
  ["dm", "Dominica"],
  ["eg", "Egipto"],
  ["ae", "Emiratos Árabes Unidos"],
  ["er", "Eritrea"],
  ["sk", "Eslovaquia"],
  ["si", "Eslovenia"],
  ["ee", "Estonia"],
  ["sz", "Esuatini"],
  ["et", "Etiopía"],
  ["ph", "Filipinas"],
  ["fi", "Finlandia"],
  ["fj", "Fiyi"],
  ["fr", "Francia"],
  ["ga", "Gabón"],
  ["gm", "Gambia"],
  ["ge", "Georgia"],
  ["gh", "Ghana"],
  ["gd", "Granada"],
  ["gr", "Grecia"],
  ["gn", "Guinea"],
  ["gq", "Guinea Ecuatorial"],
  ["gw", "Guinea-Bisáu"],
  ["gy", "Guyana"],
  ["ht", "Haití"],
  ["nl", "Países Bajos"],
  ["in", "India"],
  ["id", "Indonesia"],
  ["iq", "Irak"],
  ["ir", "Irán"],
  ["ie", "Irlanda"],
  ["is", "Islandia"],
  ["mh", "Islas Marshall"],
  ["sb", "Islas Salomón"],
  ["il", "Israel"],
  ["it", "Italia"],
  ["jm", "Jamaica"],
  ["jp", "Japón"],
  ["jo", "Jordania"],
  ["kz", "Kazajistán"],
  ["ke", "Kenia"],
  ["kg", "Kirguistán"],
  ["ki", "Kiribati"],
  ["kw", "Kuwait"],
  ["la", "Laos"],
  ["ls", "Lesoto"],
  ["lv", "Letonia"],
  ["lb", "Líbano"],
  ["lr", "Liberia"],
  ["ly", "Libia"],
  ["li", "Liechtenstein"],
  ["lt", "Lituania"],
  ["lu", "Luxemburgo"],
  ["mk", "Macedonia del Norte"],
  ["mg", "Madagascar"],
  ["my", "Malasia"],
  ["mw", "Malaui"],
  ["mv", "Maldivas"],
  ["ml", "Malí"],
  ["mt", "Malta"],
  ["ma", "Marruecos"],
  ["mu", "Mauricio"],
  ["mr", "Mauritania"],
  ["fm", "Micronesia"],
  ["md", "Moldavia"],
  ["mc", "Mónaco"],
  ["mn", "Mongolia"],
  ["me", "Montenegro"],
  ["mz", "Mozambique"],
  ["na", "Namibia"],
  ["nr", "Nauru"],
  ["np", "Nepal"],
  ["ne", "Níger"],
  ["ng", "Nigeria"],
  ["no", "Noruega"],
  ["nz", "Nueva Zelanda"],
  ["om", "Omán"],
  ["pk", "Pakistán"],
  ["pw", "Palaos"],
  ["ps", "Palestina"],
  ["pg", "Papúa Nueva Guinea"],
  ["pl", "Polonia"],
  ["pt", "Portugal"],
  ["gb", "Reino Unido"],
  ["cf", "República Centroafricana"],
  ["cz", "República Checa"],
  ["rw", "Ruanda"],
  ["ro", "Rumanía"],
  ["ru", "Rusia"],
  ["ws", "Samoa"],
  ["kn", "San Cristóbal y Nieves"],
  ["sm", "San Marino"],
  ["lc", "Santa Lucía"],
  ["st", "Santo Tomé y Príncipe"],
  ["sn", "Senegal"],
  ["rs", "Serbia"],
  ["sc", "Seychelles"],
  ["sl", "Sierra Leona"],
  ["sg", "Singapur"],
  ["sy", "Siria"],
  ["so", "Somalia"],
  ["lk", "Sri Lanka"],
  ["za", "Sudáfrica"],
  ["sd", "Sudán"],
  ["ss", "Sudán del Sur"],
  ["se", "Suecia"],
  ["ch", "Suiza"],
  ["sr", "Surinam"],
  ["th", "Tailandia"],
  ["tw", "Taiwán"],
  ["tz", "Tanzania"],
  ["tj", "Tayikistán"],
  ["tl", "Timor Oriental"],
  ["tg", "Togo"],
  ["to", "Tonga"],
  ["tt", "Trinidad y Tobago"],
  ["tn", "Túnez"],
  ["tm", "Turkmenistán"],
  ["tr", "Turquía"],
  ["tv", "Tuvalu"],
  ["ua", "Ucrania"],
  ["ug", "Uganda"],
  ["uz", "Uzbekistán"],
  ["vu", "Vanuatu"],
  ["va", "Vaticano"],
  ["vn", "Vietnam"],
  ["ye", "Yemen"],
  ["dj", "Yibuti"],
  ["zm", "Zambia"],
  ["zw", "Zimbabue"],
]

export type CountryOption = { value: string; label: string }

export const ALL_COUNTRIES: CountryOption[] = RAW_COUNTRIES.map(
  ([value, label]) => ({ value, label })
)
